"""The agent's own seat on Linux.

Wayland gives every compositor instance exactly one seat, and every seat exactly
one cursor. Adding a pointer device to the user's seat therefore *is* moving the
user's cursor — there is no second cursor to be had that way, on Hyprland or any
other wlroots compositor.

So the agent gets its own compositor. A nested Hyprland runs as one translucent
window on the user's desktop; inside it lives a second seat with a second cursor,
a second keyboard and a second clipboard. Everything the agent does goes there.
The user's pointer is never touched, and cannot be: the agent's pointer device is
bound to a socket the user's session does not share.

Backends, in order of preference:
  hyprland-nested   Hyprland inside the user's Wayland session. Tested.
  xephyr            A nested X server, for X11 desktops. Best effort.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import time
from pathlib import Path

import vpointer

STATE_DIR = Path(os.environ.get("USEPC_HOME") or (Path.home() / ".cache" / "usepc"))
SEAT_FILE = STATE_DIR / "seat.json"
SEAT_CONF = STATE_DIR / "seat.conf"
SEAT_LOG = STATE_DIR / "seat.log"
USER_CONF = Path.home() / ".config" / "usepc" / "seat.conf"

DEFAULT_WIDTH, DEFAULT_HEIGHT = 1600, 900
DEFAULT_OPACITY = 0.85
NESTED_CLASS = "aquamarine"  # what the nested compositor's host window identifies as

CONFIG_TEMPLATE = """# generated by usepc — the agent's seat. Edit ~/.config/usepc/seat.conf to override.
# Empty output name so the rule matches whatever the nested backend calls its
# output (WAYLAND-1, WL-1, ...). Scale is pinned to 1: inheriting the host's HiDPI
# scale would make the seat's logical size disagree with its pixel size, and every
# click would land in the wrong place.
monitor = , {width}x{height}@60, 0x0, 1

general {{
    gaps_in = 2
    gaps_out = 4
    border_size = 1
    col.active_border = rgba(7aa2f7aa)
}}

decoration {{
    rounding = 0
    blur {{ enabled = false }}
    shadow {{ enabled = false }}
}}

animations {{ enabled = false }}

# Off by default: Xwayland doubles startup time and the agent rarely needs X11
# apps in here. `usepc seat start --xwayland` turns it back on.
xwayland {{ enabled = {xwayland} }}

misc {{
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    background_color = 0x11131a
    vfr = false            # keep rendering while idle so captures stay fresh
    disable_autoreload = true
    focus_on_activate = true
}}

cursor {{
    no_hardware_cursors = true   # so the agent's cursor shows up in its own screenshots
    inactive_timeout = 0
}}

ecosystem {{
    no_update_news = true
    no_donation_nag = true
}}

input {{
    follow_mouse = 1
    kb_layout = {layout}
    sensitivity = 0
}}

env = XCURSOR_SIZE,32
env = USEPC_SEAT,1

# Deliberately no SUPER binds. The seat's window is `nofocus` on the host, so the
# user's own SUPER shortcuts must never be swallowed by this compositor. The agent
# types through the virtual-keyboard protocol, which does not need host focus.
bind = ALT, Q, killactive
bind = ALT, RETURN, exec, {terminal}
"""


class SeatError(RuntimeError):
    pass


# ---------------------------------------------------------------- backend pick


def _wayland_session() -> bool:
    return bool(os.environ.get("WAYLAND_DISPLAY")) or bool(
        list(Path(os.environ.get("XDG_RUNTIME_DIR", "/tmp")).glob("wayland-[0-9]*"))
    )


def backend() -> str:
    if shutil.which("Hyprland") and _wayland_session():
        return "hyprland-nested"
    if shutil.which("Xephyr"):
        return "xephyr"
    return "none"


def _host_display() -> str:
    disp = os.environ.get("WAYLAND_DISPLAY")
    if disp:
        return disp
    runtime = Path(os.environ.get("XDG_RUNTIME_DIR", "/tmp"))
    socks = sorted(p for p in runtime.glob("wayland-[0-9]*") if not p.name.endswith(".lock"))
    if not socks:
        raise SeatError("no Wayland session socket found — is a compositor running?")
    return socks[0].name


def _terminal() -> str:
    for term in ("alacritty", "foot", "kitty", "ghostty", "wezterm", "xterm"):
        if shutil.which(term):
            return term
    return "alacritty"


def _kb_layout() -> str:
    """Inherit the user's keyboard layout so typing produces the right glyphs."""
    try:
        out = subprocess.run(["hyprctl", "getoption", "input:kb_layout", "-j"],
                             capture_output=True, text=True, timeout=3).stdout
        layout = json.loads(out).get("str", "").strip()
        if layout:
            return layout
    except Exception:
        pass
    return "us"


# ---------------------------------------------------------------- state on disk


def _read_state() -> dict:
    try:
        return json.loads(SEAT_FILE.read_text())
    except Exception:
        return {}


def _write_state(state: dict) -> None:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    tmp = SEAT_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(state, indent=2))
    tmp.replace(SEAT_FILE)


def _alive(pid: int) -> bool:
    try:
        os.kill(int(pid), 0)
        return True
    except Exception:
        return False


def _instances() -> list[dict]:
    try:
        out = subprocess.run(["hyprctl", "instances", "-j"],
                             capture_output=True, text=True, timeout=4).stdout
        return json.loads(out)
    except Exception:
        return []


# ---------------------------------------------------------------- hyprctl, but pointed at the seat


def hyprctl(args: list[str], json_out: bool = False, timeout: float = 5.0):
    """Run hyprctl against the agent's compositor, never the user's."""
    state = status()
    if not state.get("running"):
        raise SeatError("the agent seat is not running")
    cmd = ["hyprctl", "-i", state["signature"]] + args + (["-j"] if json_out else [])
    env = dict(os.environ)
    env["HYPRLAND_INSTANCE_SIGNATURE"] = state["signature"]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, env=env)
    if proc.returncode != 0:
        raise SeatError(f"hyprctl {' '.join(args)} failed: {(proc.stderr or proc.stdout).strip()}")
    return json.loads(proc.stdout) if json_out else proc.stdout.strip()


def seat_env(extra: dict | None = None) -> dict:
    """Environment that makes a child process land inside the agent seat."""
    state = status()
    if not state.get("running"):
        raise SeatError("the agent seat is not running")
    env = dict(os.environ)
    env["WAYLAND_DISPLAY"] = state["display"]
    env["HYPRLAND_INSTANCE_SIGNATURE"] = state["signature"]
    env["XDG_CURRENT_DESKTOP"] = "Hyprland"
    env["XDG_SESSION_TYPE"] = "wayland"
    env["USEPC_SEAT"] = "1"
    env.pop("DISPLAY", None)  # let the nested Xwayland claim its own
    if extra:
        env.update(extra)
    return env


# ---------------------------------------------------------------- lifecycle


def status() -> dict:
    state = _read_state()
    if not state:
        return {"running": False, "backend": backend()}
    if not _alive(state.get("pid", -1)):
        return {"running": False, "backend": backend(), "stale": True}
    if state.get("backend") == "hyprland-nested":
        match = next((i for i in _instances() if i.get("pid") == state["pid"]), None)
        if not match:
            return {"running": False, "backend": backend(), "stale": True}
        state["display"] = match["wl_socket"]
        state["signature"] = match["instance"]
    state["running"] = True
    return state


def geometry() -> tuple[int, int]:
    """Live size of the seat's output — it follows the host window, so ask every time."""
    state = status()
    if not state.get("running"):
        raise SeatError("the agent seat is not running")
    if state.get("backend") == "xephyr":
        return int(state["width"]), int(state["height"])
    mons = hyprctl(["monitors"], json_out=True)
    if not mons:
        raise SeatError("the agent seat reports no output")
    mon = mons[0]
    scale = mon.get("scale") or 1
    return int(mon["width"] / scale), int(mon["height"] / scale)


def start(width: int = DEFAULT_WIDTH, height: int = DEFAULT_HEIGHT,
          opacity: float = DEFAULT_OPACITY, visible: bool = True,
          workspace: str | None = None, xwayland: bool = False) -> dict:
    existing = status()
    if existing.get("running"):
        return existing
    kind = backend()
    # Remember what the user was working in, so we can hand focus straight back.
    previous = None
    try:
        previous = json.loads(subprocess.run(["hyprctl", "activewindow", "-j"],
                                             capture_output=True, text=True,
                                             timeout=3).stdout).get("address")
    except Exception:
        pass
    if kind == "hyprland-nested":
        state = _start_hyprland(width, height, xwayland)
    elif kind == "xephyr":
        state = _start_xephyr(width, height)
    else:
        raise SeatError(
            "no way to give the agent its own seat on this machine.\n"
            "  Wayland: install Hyprland (it can run nested inside your session)\n"
            "  X11:     install xorg-server-xephyr + xdotool"
        )
    _write_state(state)
    if kind == "hyprland-nested":
        _place_host_window(state["pid"], width, height, opacity, visible, workspace, previous)
    return status()


def _start_hyprland(width: int, height: int, xwayland: bool = False) -> dict:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    conf = USER_CONF if USER_CONF.exists() else SEAT_CONF
    if conf is SEAT_CONF:
        SEAT_CONF.write_text(CONFIG_TEMPLATE.format(
            width=width, height=height, terminal=_terminal(), layout=_kb_layout(),
            xwayland="true" if xwayland else "false"))
    env = dict(os.environ)
    env["WAYLAND_DISPLAY"] = _host_display()          # forces the nested wayland backend
    env.pop("HYPRLAND_INSTANCE_SIGNATURE", None)      # this is a new instance, not the user's
    env["HYPRLAND_NO_CRASHREPORTER"] = "1"
    env["HYPRLAND_NO_SD_NOTIFY"] = "1"
    # Register these BEFORE the window exists. Applying nofocus after the fact is
    # too late — the window has already taken the keyboard, and the user's SUPER
    # binds stop working the moment it maps.
    for rule in (f"noinitialfocus, class:^({NESTED_CLASS})$",
                 f"nofocus, class:^({NESTED_CLASS})$"):
        subprocess.run(["hyprctl", "keyword", "windowrule", rule],
                       capture_output=True, text=True, timeout=4)
    known = {i["pid"] for i in _instances()}
    log = SEAT_LOG.open("a")
    log.write(f"\n=== agent seat starting {time.strftime('%Y-%m-%d %H:%M:%S')} ===\n")
    log.flush()
    proc = subprocess.Popen(["Hyprland", "-c", str(conf)], stdout=log, stderr=subprocess.STDOUT,
                            start_new_session=True, env=env)
    deadline = time.time() + 15
    while time.time() < deadline:
        time.sleep(0.3)
        if proc.poll() is not None:
            tail = SEAT_LOG.read_text()[-800:]
            raise SeatError(f"the nested compositor exited immediately:\n{tail}")
        match = next((i for i in _instances()
                      if i["pid"] == proc.pid or (i["pid"] not in known and _alive(i["pid"]))), None)
        if match:
            # give it a moment to bind its protocols before anyone pokes at it
            for _ in range(20):
                if vpointer.supported(match["wl_socket"]):
                    break
                time.sleep(0.25)
            return {"backend": "hyprland-nested", "pid": match["pid"],
                    "display": match["wl_socket"], "signature": match["instance"],
                    "width": width, "height": height, "started": time.time(),
                    "config": str(conf)}
    proc.terminate()
    raise SeatError(f"the nested compositor never registered an instance (see {SEAT_LOG})")


def _start_xephyr(width: int, height: int) -> dict:
    display = ":" + str(_free_x_display())
    log = SEAT_LOG.open("a")
    proc = subprocess.Popen(
        ["Xephyr", display, "-screen", f"{width}x{height}", "-resizeable", "-title", "usepc agent seat"],
        stdout=log, stderr=subprocess.STDOUT, start_new_session=True)
    time.sleep(1.5)
    if proc.poll() is not None:
        raise SeatError(f"Xephyr exited immediately (see {SEAT_LOG})")
    for wm in ("openbox", "i3", "fluxbox", "marco"):
        if shutil.which(wm):
            subprocess.Popen([wm], env={**os.environ, "DISPLAY": display},
                             stdout=log, stderr=subprocess.STDOUT, start_new_session=True)
            break
    return {"backend": "xephyr", "pid": proc.pid, "display": display,
            "signature": display, "width": width, "height": height,
            "started": time.time()}


def _free_x_display() -> int:
    for n in range(9, 40):
        if not Path(f"/tmp/.X11-unix/X{n}").exists():
            return n
    raise SeatError("no free X display number")


def _place_host_window(pid: int, width: int, height: int, opacity: float,
                       visible: bool, workspace: str | None,
                       previous: str | None = None) -> None:
    """Float the seat's window, dim it, and — critically — deny it keyboard focus.

    A focused nested compositor eats every key the user presses, SUPER included,
    which makes their own keybinds look broken. `nofocus` keeps the host in charge
    of the keyboard; the agent does not need host focus because it types straight
    into the seat over the virtual-keyboard protocol.
    """
    address = None
    for _ in range(20):
        try:
            clients = json.loads(subprocess.run(["hyprctl", "clients", "-j"],
                                                capture_output=True, text=True, timeout=4).stdout)
        except Exception:
            clients = []
        match = next((c for c in clients if c.get("pid") == pid), None)
        if match:
            address = match["address"]
            break
        time.sleep(0.3)
    if not address:
        return
    target = f"address:{address}"
    steps = [
        ["setprop", target, "nofocus", "1", "lock"],
        ["dispatch", "setfloating", target],
        ["dispatch", "resizewindowpixel", f"exact {width} {height},{target}"],
        ["setprop", target, "opacity", f"{opacity:.2f}", "lock"],
        ["setprop", target, "noshadow", "1", "lock"],
    ]
    if workspace:
        steps.append(["dispatch", "movetoworkspacesilent", f"{workspace},{target}"])
    elif visible:
        steps.append(["dispatch", "centerwindow"])
    # Deliberately no focuswindow call to "restore" the user: on Hyprland that
    # warps their cursor, which is the one thing this tool promises never to do.
    # The noinitialfocus rule means focus was never taken in the first place.
    for step in steps:
        subprocess.run(["hyprctl"] + step, capture_output=True, text=True, timeout=4)


def _host_address() -> str:
    state = status()
    if not state.get("running"):
        raise SeatError("the agent seat is not running")
    clients = json.loads(subprocess.run(["hyprctl", "clients", "-j"], capture_output=True,
                                        text=True, timeout=4).stdout)
    match = next((c for c in clients if c.get("pid") == state["pid"]), None)
    if not match:
        raise SeatError("the seat's window is not on the user's desktop right now")
    return match["address"]


def handoff() -> str:
    """Let the human type into the seat: lift nofocus and focus it.

    Their SUPER keybinds stop working while the seat holds focus — that is what
    `reclaim` is for.
    """
    address = _host_address()
    subprocess.run(["hyprctl", "setprop", f"address:{address}", "nofocus", "0", "lock"],
                   capture_output=True, timeout=4)
    subprocess.run(["hyprctl", "dispatch", "focuswindow", f"address:{address}"],
                   capture_output=True, timeout=4)
    return ("seat focused — your keystrokes now go to it, including SUPER. "
            "Run `usepc seat reclaim` to give your keybinds back.")


def reclaim() -> str:
    """Take focus back off the seat and restore the user's keybinds."""
    address = _host_address()
    subprocess.run(["hyprctl", "setprop", f"address:{address}", "nofocus", "1", "lock"],
                   capture_output=True, timeout=4)
    subprocess.run(["hyprctl", "dispatch", "focuscurrentorlast"], capture_output=True, timeout=4)
    return "seat set back to nofocus — your keyboard and SUPER binds are yours again"


def stop() -> str:
    state = _read_state()
    if not state:
        return "no agent seat recorded"
    pid = state.get("pid")
    if pid and _alive(pid):
        try:
            os.killpg(os.getpgid(pid), 15)
        except Exception:
            try:
                os.kill(pid, 15)
            except Exception:
                pass
        for _ in range(20):
            if not _alive(pid):
                break
            time.sleep(0.2)
        if _alive(pid):
            try:
                os.killpg(os.getpgid(pid), 9)
            except Exception:
                pass
    SEAT_FILE.unlink(missing_ok=True)
    return f"agent seat stopped (pid {pid})"


def ensure(**opts) -> dict:
    """Start the seat if it isn't up. Called by every action, so actions Just Work."""
    state = status()
    if state.get("running"):
        return state
    return start(**opts)


# ---------------------------------------------------------------- acting in the seat


def pointer() -> vpointer.VirtualPointer:
    state = ensure()
    if state["backend"] == "xephyr":
        raise SeatError("xephyr seats are driven with xdotool, not a wayland pointer")
    return vpointer.VirtualPointer(state["display"], geometry())


def cursor_position() -> tuple[int, int]:
    state = ensure()
    if state["backend"] == "xephyr":
        out = subprocess.run(["xdotool", "getmouselocation", "--shell"], capture_output=True,
                             text=True, env={**os.environ, "DISPLAY": state["display"]}).stdout
        vals = dict(line.split("=", 1) for line in out.strip().splitlines() if "=" in line)
        return int(vals.get("X", 0)), int(vals.get("Y", 0))
    raw = hyprctl(["cursorpos"])
    x, y = (int(v.strip()) for v in raw.split(","))
    return x, y


def _xdotool(args: list[str]) -> None:
    state = ensure()
    if not shutil.which("xdotool"):
        raise SeatError("xdotool is needed to drive an xephyr seat")
    subprocess.run(["xdotool"] + args, check=True,
                   env={**os.environ, "DISPLAY": state["display"]})


def move(x: float, y: float) -> None:
    state = ensure()
    if state["backend"] == "xephyr":
        return _xdotool(["mousemove", str(int(x)), str(int(y))])
    with pointer() as ptr:
        ptr.move(x, y)
        ptr.flush()


def click(x: float | None = None, y: float | None = None, button: str = "left",
          count: int = 1) -> None:
    state = ensure()
    if state["backend"] == "xephyr":
        if x is not None:
            _xdotool(["mousemove", str(int(x)), str(int(y))])
        return _xdotool(["click", "--repeat", str(count),
                         {"left": "1", "middle": "2", "right": "3"}.get(button, "1")])
    with pointer() as ptr:
        if x is not None and y is not None:
            ptr.move(x, y)
            time.sleep(0.12)
        ptr.click(button, count)
        ptr.flush()


def scroll(notches: int, x: float | None = None, y: float | None = None,
           horizontal: bool = False) -> None:
    with pointer() as ptr:
        if x is not None and y is not None:
            ptr.move(x, y)
            time.sleep(0.1)
        ptr.scroll(notches, horizontal)
        ptr.flush()


def drag(x1: float, y1: float, x2: float, y2: float, button: str = "left",
         steps: int = 24) -> None:
    with pointer() as ptr:
        ptr.drag(x1, y1, x2, y2, button, steps)
        ptr.flush()


def type_text(text: str, delay_ms: int = 12) -> None:
    state = ensure()
    if state["backend"] == "xephyr":
        return _xdotool(["type", "--delay", str(delay_ms), text])
    if not shutil.which("wtype"):
        raise SeatError("wtype is needed to type into a wayland seat (pacman -S wtype)")
    proc = subprocess.run(["wtype", "-d", str(max(0, min(delay_ms, 200))), "-"],
                          input=text, capture_output=True, text=True, env=seat_env())
    if proc.returncode != 0:
        raise SeatError(f"wtype failed: {(proc.stderr or proc.stdout).strip()}")


MODIFIERS = {"ctrl": "ctrl", "control": "ctrl", "shift": "shift", "alt": "alt", "opt": "alt",
             "option": "alt", "altgr": "altgr", "super": "logo", "meta": "logo", "cmd": "logo",
             "win": "logo", "logo": "logo"}
KEY_ALIASES = {"enter": "Return", "return": "Return", "esc": "Escape", "escape": "Escape",
               "tab": "Tab", "space": "space", "backspace": "BackSpace", "bs": "BackSpace",
               "del": "Delete", "delete": "Delete", "up": "Up", "down": "Down", "left": "Left",
               "right": "Right", "home": "Home", "end": "End", "pgup": "Prior",
               "pageup": "Prior", "pgdn": "Next", "pagedown": "Next", "insert": "Insert",
               "menu": "Menu", "print": "Print", "minus": "minus", "plus": "plus",
               "equal": "equal"}


def _keysym(token: str) -> str:
    low = token.lower()
    if low in KEY_ALIASES:
        return KEY_ALIASES[low]
    if len(token) == 1:
        return token
    if low.startswith("f") and low[1:].isdigit():
        return "F" + low[1:]
    return token


def press(combo: str) -> None:
    """'ctrl+shift+t', 'Return', 'alt+F4' — one keystroke with modifiers held."""
    state = ensure()
    parts = [p for p in combo.replace(" ", "").split("+") if p]
    if not parts:
        raise SeatError("empty key combo")
    if state["backend"] == "xephyr":
        return _xdotool(["key", "+".join(parts)])
    mods, key = [], None
    for i, part in enumerate(parts):
        mod = MODIFIERS.get(part.lower())
        if mod and i < len(parts) - 1:
            mods.append(mod)
        else:
            key = part
    if key is None:
        raise SeatError(f"{combo!r} has modifiers but no key")
    args: list[str] = []
    for mod in mods:
        args += ["-M", mod]
    args += ["-k", _keysym(key)]
    for mod in reversed(mods):
        args += ["-m", mod]
    proc = subprocess.run(["wtype"] + args, capture_output=True, text=True, env=seat_env())
    if proc.returncode != 0:
        raise SeatError(f"wtype failed: {(proc.stderr or proc.stdout).strip()}")


def paste(text: str, combo: str = "ctrl+v") -> None:
    """Uses the *seat's* clipboard — the user's clipboard is left alone."""
    env = seat_env()
    if not shutil.which("wl-copy"):
        raise SeatError("wl-clipboard is needed for paste (pacman -S wl-clipboard)")
    subprocess.run(["wl-copy"], input=text, text=True, env=env, check=True)
    time.sleep(0.15)
    press(combo)


def spawn(command: str) -> int:
    """Launch something inside the seat. Returns its pid."""
    env = seat_env()
    proc = subprocess.Popen(["/bin/sh", "-lc", command], env=env, start_new_session=True,
                            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return proc.pid


def windows() -> list[dict]:
    state = ensure()
    if state["backend"] == "xephyr":
        out = subprocess.run(["xdotool", "search", "--onlyvisible", "--name", ""],
                             capture_output=True, text=True,
                             env={**os.environ, "DISPLAY": state["display"]}).stdout
        return [{"id": wid} for wid in out.split()]
    return [
        {"class": c.get("class"), "title": c.get("title"), "pid": c.get("pid"),
         "at": c.get("at"), "size": c.get("size"), "focused": c.get("focusHistoryID") == 0,
         "address": c.get("address")}
        for c in hyprctl(["clients"], json_out=True)
    ]


def focus(match: str) -> str:
    for win in windows():
        haystack = f"{win.get('class', '')} {win.get('title', '')}".lower()
        if match.lower() in haystack:
            hyprctl(["dispatch", "focuswindow", f"address:{win['address']}"])
            return f"focused {win.get('class')} — {win.get('title')}"
    raise SeatError(f"no window in the agent seat matches {match!r}")


def shot(dest: Path, scale: float = 0.66, quality: int = 62,
         region: str | None = None, window: str | None = None) -> Path:
    """Capture the seat. grim scales and JPEG-encodes, so no Pillow needed."""
    state = ensure()
    dest.parent.mkdir(parents=True, exist_ok=True)
    if state["backend"] == "xephyr":
        if not shutil.which("import"):
            raise SeatError("imagemagick is needed to capture an xephyr seat")
        subprocess.run(["import", "-window", "root", str(dest)], check=True,
                       env={**os.environ, "DISPLAY": state["display"]})
        return dest
    args = ["grim", "-c", "-t", "jpeg", "-q", str(int(quality)), "-s", f"{scale:g}"]
    if window:
        target = next((w for w in windows()
                       if window.lower() in f"{w.get('class','')} {w.get('title','')}".lower()), None)
        if not target:
            raise SeatError(f"no window in the agent seat matches {window!r}")
        x, y = target["at"]
        w, h = target["size"]
        args += ["-g", f"{x},{y} {w}x{h}"]
    elif region:
        args += ["-g", region]
    args.append(str(dest))
    proc = subprocess.run(args, capture_output=True, text=True, env=seat_env())
    if proc.returncode != 0:
        raise SeatError(f"grim failed: {(proc.stderr or proc.stdout).strip()}")
    return dest


def set_opacity(opacity: float) -> str:
    """Dim (or un-dim) the seat's window on the user's desktop."""
    state = status()
    if not state.get("running"):
        raise SeatError("the agent seat is not running")
    clients = json.loads(subprocess.run(["hyprctl", "clients", "-j"], capture_output=True,
                                        text=True, timeout=4).stdout)
    match = next((c for c in clients if c.get("pid") == state["pid"]), None)
    if not match:
        raise SeatError("the seat's window is not on the user's desktop right now")
    subprocess.run(["hyprctl", "setprop", f"address:{match['address']}", "opacity",
                    f"{opacity:.2f}", "lock"], capture_output=True, timeout=4)
    return f"seat window opacity set to {opacity:.2f}"
